
name: 'dbt_tutorial'
version: '0.1'
profile: 'dbt_tutorial'
config-version: 2

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

models:
  dbt_tutorial:
      materialized: table
      staging:
        materialized: view
