
name: 'dbt_test'
version: '0.1'
profile: 'dbt_dev'
config-version: 2

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"
  - "logs"

models:
  dbt_test:
    materialized: table
    staging:
      materialized: view
