services:
  postgres:
    image: "postgres:14-alpine"
    environment:
      - POSTGRES_PASSWORD=demopsw
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
networks:
    default:
        name: dbt_network