
# For more information on how to configure this file, please see:
# https://docs.getdbt.com/docs/profile

#Ref : https://docs.getdbt.com/docs/configure-your-profile
#dbt run --profiles-dir path/to/directory
#export DBT_PROFILES_DIR=path/to/directory


dbt_dev:
  target: default
  outputs:
    default:
      type: postgres
      host: dbtpostgres.cqs0u8dcednc.eu-west-1.rds.amazonaws.com
      user: postgres
      password: "{{ env_var('DBT_PASSWORD') }}"
      port: 5432
      dbname: dbt
      schema: dbt_dev
      threads: 1

dbt_prod:
  target: default
  outputs:
    default:
      type: postgres
      host: dbtpostgres.cqs0u8dcednc.eu-west-1.rds.amazonaws.com
      user: postgres
      password: "{{ env_var('DBT_PASSWORD') }}"
      port: 5432
      dbname: dbt
      schema: dbt_prod
      threads: 1
